# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('is_done', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'db_table': 'todolist',
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.TodoList', verbose_name='List'),
        ),
    ]
